# ===========================
# APPLICATION
# ===========================
spring.application.name=banking-app
server.port=${PORT:8081}
# ===========================
# DATASOURCE (H2)
# ===========================
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
# ===========================
# SPRINGDOC / SWAGGER
# ===========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
# ===========================
# JACKSON
# ===========================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false
